### ISSUE TITLE
Send transactions directly to the scene builder thread when possible

### ISSUE THREAD

**Issue by ktaeleman** [FirefoxGraphics/planning#48]
Currently transactions that trigger scene building first go through the render backend, then some resources are collected (font, blobs) and sent to the scene builder. If the render backend is busy this delays the scene being processed, causing extra latency for layout transactions.

With ipc_channel removed, we can move the few hash maps on that store data we send to the scene builder, keep them at the API level instead and send messages directly to the scene builder. It should make things simpler (no need to remember which data is pre/post scene building on the render backend, everything is post-scene building) and reduce latency in some cases.

---
🐞 Issue is synchronized with Bugzilla [Bug 1612440](https://bugzilla.mozilla.org/show_bug.cgi?id=1612440)

**Comment by huwdp** [comment]
Should this task be done as the code looks like is in moz central?

**Comment by nical** [comment]
It's not complete yet.

**Comment by ktaeleman** [comment]
Upstream bug has been closed with the following resolution: FIXED.
